# Generated by Django 3.1.3 on 2020-11-25 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='nome',
            field=models.CharField(help_text='Nome da empresa', max_length=100),
        ),
    ]
