# Generated by Django 3.1.3 on 2020-11-25 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0002_auto_20201124_2337'),
        ('registro_horas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrohoras',
            name='funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
